production:
  phpSettings:
    display_startup_errors: false
    display_errors: false
  bootstrap:
    path: APPLICATION_PATH/Bootstrap.php
    class: Bootstrap
  appnamespace: MyProj
  siteName: マイ X プロジェクト
  resources:
    frontController:
      controllerDirectory: APPLICATION_PATH/controllers
      moduleDirectory: APPLICATION_PATH/modules
      params:
        displayExceptions: false
    layout:
      layoutPath: APPLICATION_PATH/layouts/scripts/
    ## Database
    db:
      adapter: pdo_mysql
      params:
        host: localhost
        dbname: test
        username: root
        password: root
    ## Session
    # table to use
    # CREATE TABLE session (
    #   id char(32),
    #   modified int,
    #   lifetime int,
    #   data text,
    #   PRIMARY KEY (`id`)
    # );
    session:
      # remember_me_seconds: 864000
      saveHandler:
        class: Zend_Session_SaveHandler_DbTable
        options:
          name: session
          primary: id
          modifiedColumn: modified
          dataColumn: data
          lifetimeColumn: lifetime
    ## Router
    router:
      routes:
        - 
          author:
            type: Zend_Controller_Router_Route
            route: author/:name/:id/*
            defaults:
              controller: Trial
              action: added-route
              name: tom
              id: 1922

staging:
  _extends: production

testing:
  _extends: production
  phpSettings:
    display_startup_errors: true
    display_errors: true

development:
  _extends: production
  phpSettings:
    display_startup_errors: true
    display_errors: true
  resources:
    frontController:
      params:
        displayExceptions: true
